### ISSUE TITLE
uninstall AutoScriptVPN-Xray？

### ISSUE THREAD

**Issue by ergatea** [praiman99/AutoScriptVPN-Xray#1]

**Comment by praiman99** [comment]
Hi thanks for willing to contact us, first of all sorry for late reply because busy work for uninstall all the script from this github you need to rebuild/rebuilt you vps on your vps panel only for full fresh and all file delete surely

**Comment by ergatea** [comment]
thanks

PR Aiman ***@***.***> 于2023年1月31日周二 16:41写道：
